### PR TITLE
xor 64 bits at a time

### PR DESCRIPTION
**Pull request by pnutus**
Dunno if this improves performance, should probably check

### CODE REVIEW

**Comment by Liffon** [comment]
Hm, what happens if the message length is not a multiple of 64 bits?

**Comment by Liffon** [comment]
Answer: it writes to invalid memory! (I checked.) Fix this and I'll merge it ;)

**Comment by pnutus** [comment]
Oh, I thought you always allocated in chunks divisible by 8 bytes. Must have misread.

**Comment by pnutus** [comment]
I don't see this problem, what did you use to test? Is [this](https://github.com/pnutus/otp/blob/xor-chunks/otp.cpp#L63-L66) throwing a wrench into my assumptions? I do not understand what the !isatty is doing. When does the code take that path and why?

I did fix a typo and add a comment about needing 64-bit-aligned allocations.

**Comment by Liffon** [comment]
The code takes that path when the user didn't provide arguments for input
file and input is taken from stdin. Then the input stream "is a tty". If it
isn't, we can query the file size and read all of it at once. If it is, though, we can't query file size and thus have to decide a chunk size to read at a time.
_Edit:_ Sorry, I meant it takes the !isatty path when input _is_ a file (not a tty) and the else path that uses chunk_size when input is stdin.

It's really a bit redundant and the only reason for not always reading in
chunks is possibly better performance for large files, but I haven't
actually measured how much is gained. In any case, it only allocates
exactly as many bytes as the input is before EOF.

**Comment by Liffon** [comment]
Oh, and I used [Valgrind](http://valgrind.org/) to check.

**Comment by Liffon** [comment]
I just realized two things:
- You're right that the message data is allocated aligned to 64 bits, but _only if input is not a file_. If input is a file, it allocates exactly as many bytes as the file length and if it's a tty, e.g. stdin, it allocates in chunks of 1024.
- This is not what causes the invalid write I found with Valgrind. We don't ever write to the message data in `xorData()`, but only to the result data, which is _always_ allocated to be exactly as long as the length of the message.

Proposed way to do this **nicely**:
Change the allocation function `allocateData()` so that it always does 64-bit-aligned allocations (also its friend `reallocateData()`).

Alternatively – but a bit less nice – we could just change the allocation made by `xorData()`, but then we would still potentially have invalid reads from just outside the end of the message and key data. I can't imagine this will be a real problem, though.

You wanna do it or shall I?

**Comment by pnutus** [comment]
I think it works now. I code, you review ^^

**Comment by pnutus** [comment]
(The weird thing is, it worked for me before – even for files. But it might have something to do with your refactoring, I suppose.)

**Comment by Liffon** [comment]
Merged! I put back a line that you deleted; see comment.

When you say it worked before, do you mean it stopped working? Because the way I see it, it probably always works the way you did it on 64-bit architectures since allocations almost always start at 64-bit aligned addresses so we never overwrite anything with data in it. So it's mostly a cosmetic fix. ^^

**Comment by pnutus** [comment]
The deleted line was a mistake. I deleted it while debugging and forgot to add it back when I realised where the real problem was.

That makes sense. No, it didn't stop working, it always worked. So you never had a problem with `BAD_ACCESS` either?

**Comment by pnutus** [comment]
Btw, what architectures are ever less than 64-bit nowadays? Does it make sense to even think about 32-bit? (Except mobile devices, but this is not for them, I'm thinking.)

**Comment by Liffon** [comment]
Nope, I never saw it other than when running through Valgrind. But I found it more aesthetic to have NO MEMORY ERRORS, even if they didn't matter – plus, I didn't realize it would never actually be a problem until I took a long hard look at it. Anyway, feels good to have it fixed.

On the architecture part: let's not discriminate against security nuts running on an old x86 disconnected from Internet since 1994, shall we? ;)
I'm not sure if it applies to all 64-bit architectures though. Maybe not all aligns for 64-bit.

**Comment by Liffon** [comment]
I just discovered another memory glitch; this time in `reallocateData()`. Valgrind complains about uninitialized values and the warning goes away when I do a naïve clear byte-by-byte. We never discovered it before since `reallocateData()` was originally not used in `otp.cpp`, but it popped up when working on `sha-256.cpp`. I think it sometimes gives the wrong answer when computing hashes, especially when from the empty string.

The reason this is a problem (at least I think it is, but it doesn't seem to appear consistently) is because `sha256()` depends on the reallocated data being cleared properly, which the stuff in `otp.cpp` doesn't.

Oh, and the code that uses this is in the `sha-256` branch. The one in `master` is outdated and should not be there.

**Comment by pnutus** [comment]
Yeah, it's probably an off-by-one error. I haven't been super careful about making sure the loops do the right thing. Do you have any good means of debugging? I've been using CLI LLDB, and (just like CLI GDB) it's a pain to use.

**Comment by Liffon** [comment]
Nope, I've only been using cli gdb. Thinking of switching to lldb. Is it
any better?
lör 23 maj 2015 kl. 09:25 skrev Pontus Granström notifications@github.com:

**Comment by pnutus** [comment]
On the command lin it's pretty much the same I think. A few different commands. Maybe it's faster. Haven't used any of them enough to say more than "I want a debugger integrated in the editor." Isn't there something like that for vim?

**Comment by Liffon** [comment]
There probably is. Not sure if I necessarily want my debugger integrated in the editor, but something better than gdb would sure be nice.

**Pull request merged**
